esphome:
  name: house_master

# Import packages from GitHub for modular thermostats
packages:
  # ========== HARDWARE (FIX - nu se modifică) ==========
  hardware: !include hardware.yaml
  
  # ========== THERMOSTATS ==========
  thermostat_02: !include
    file: modbus_thermostats.yaml
    vars:
      thermo_id: "thermo_02"
      thermo_name: "Bedroom Thermostat"
      thermo_address: "2"
  
  thermostat_03: !include
    file: modbus_thermostats.yaml
    vars:
      thermo_id: "thermo_03"
      thermo_name: "Living Room Thermostat"
      thermo_address: "3"
  
  thermostat_04: !include
    file: modbus_thermostats.yaml
    vars:
      thermo_id: "thermo_04"
      thermo_name: "Kitchen Thermostat"
      thermo_address: "4"
  
  # Add more thermostats as needed:
  # thermostat_05: !include
  #   file: modbus_thermostats.yaml
  #   vars:
  #     thermo_id: "thermo_05"
  #     thermo_name: "Bathroom Thermostat"
  #     thermo_address: "5"
  
  # ========== I/O EXTENSIONS (Light Controls) ==========
  # Connect 2 existing inputs (ext_in) to 1 existing light
  # Example: ext_in23 & ext_in24 control pwm_0
  # living_light: !include
  #   file: io_extension.yaml
  #   vars:
  #     input_id_up: "ext_in23"      # Choose ANY input for dim up
  #     input_id_down: "ext_in24"    # Choose ANY input for dim down
  #     light_id: "pwm_0"            # Choose ANY existing light
  #     dim_step: "5%"
  #     dim_delay: "0.1s"


esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:
  level: DEBUG

# Enable Home Assistant API
api:
  encryption:
    key: "WmpyyQoIZY3IzptdKGdFnE7nTLKOgShjoxr0Fz3iIg4="

ota:
  - platform: esphome
    password: "1572bd0bf17e44558ef03c34c6256c69"

mqtt:
  broker: 192.168.0.197
  username: phateks
  password: papagalulr0su

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
#  manual_ip: 
#    static_ip: 192.168.0.201
#    gateway: 192.168.0.1
#    subnet: 255.255.255.0

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "A4S Fallback Hotspot"
    password: "wiPNK3dzwd6G"

captive_portal:

# Individual outputs (pentru termostat principal - adresa 1)
switch:
  - platform: output
    id: thermo_dummy_switch
    name: "ThermoDummySwitch"
    output: dummy_switch
    internal: True
    
  - platform: modbus_controller
    modbus_controller_id: thermostat_modbus
    id: thermostat_state
    name: "Thermostat On/Off"
    address: 0x0000
    register_type: holding
    bitmask: 1
    on_turn_on:
      - climate.control:
          id: thermo
          mode: "HEAT"
    on_turn_off:
      - climate.control:
          id: thermo
          mode: "OFF"

# Modbus controller pentru termostat principal (adresa 1)
modbus_controller:
  - id: thermostat_modbus
    modbus_id: modbus1
    address: 1
    command_throttle: 200ms
    setup_priority: -10

######### dallas sensor ##########
one_wire:
  - platform: gpio
    pin: GPIO5
    id: evi_dallas

sensor:
  - platform: modbus_controller
    modbus_controller_id: thermostat_modbus
    id: room_temperature
    name: "Room Temperature"
    address: 0x0001
    register_type: holding
    unit_of_measurement: "°C"
    value_type: U_WORD
    accuracy_decimals: 1
    filters:
      - lambda: return x * 0.1;

  - platform: modbus_controller
    modbus_controller_id: thermostat_modbus
    id: external_temperature
    name: "External Temperature"
    address: 0x0005
    register_type: holding
    unit_of_measurement: "°C"
    value_type: U_WORD
    accuracy_decimals: 1
    filters:
      - lambda: return x * 0.1;

  - platform: modbus_controller
    modbus_controller_id: thermostat_modbus
    id: target_temperature
    name: "Target Temperature"
    address: 0x0004
    register_type: holding
    unit_of_measurement: "°C"
    value_type: U_WORD
    accuracy_decimals: 1
    filters:
      - lambda: return x * 0.1;
    internal: true
    
  - platform: dallas_temp
    id: sensor_evi
    name: "Evi Dallas Temp"
    address: 0xd70008039ae53810
    update_interval: 10s
    accuracy_decimals: 1

number:
  - platform: modbus_controller
    modbus_controller_id: thermostat_modbus
    id: set_temperature
    name: "Set Temperature"
    address: 0x0004  # Address 40005 in the documentation
    register_type: holding
    unit_of_measurement: "°C"
    value_type: U_WORD
    min_value: 15
    max_value: 35
    step: 0.5
    multiply: 10
    on_value:
      - climate.control:
          id: thermo
          target_temperature: !lambda return x;
    internal: true

climate:
  - platform: thermostat
    id: thermo
    name: "ModBus Thermostat"
    sensor: room_temperature
    visual:
      min_temperature: 15 °C
      max_temperature: 35 °C
      temperature_step: 0.5 °C
    min_idle_time: 10s
    min_heating_off_time: 10s
    min_heating_run_time: 10s
    heat_overrun: 0.1
    heat_deadband: 0.2
    heat_action:
      - delay: 10ms
    idle_action:
      - delay: 10ms
    on_control:
      - lambda: |-
          auto target = x.get_target_temperature();
          if (target.has_value() && (*target != id(set_temperature).state))
            id(set_temperature).make_call().set_value(*target).perform();
          auto state = x.get_mode();
          if (state.has_value()) {
            bool onoff = *state != climate::CLIMATE_MODE_OFF;
            if (onoff != id(thermostat_state).state) {
              if (onoff)
                id(thermostat_state).turn_on();
              else
                id(thermostat_state).turn_off();
            }
          }

  - platform: thermostat
    id: living_thermostat
    name: "Evi Thermostat"
    sensor: sensor_evi
    visual:
      min_temperature: 15 °C
      max_temperature: 35 °C
      temperature_step: 0.1 °C
    min_idle_time: 10s
    min_heating_off_time: 10s
    min_heating_run_time: 10s
    heat_action:
      - switch.turn_on: thermo_dummy_switch
    idle_action:
      - switch.turn_off: thermo_dummy_switch
    heat_overrun: 0.05
    heat_deadband: 0.15